### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/batch#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [x] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by GroophyLifefor** [comment]
Hi @ErikSchierboom , 

I am currently preparing for the university entrance exam, which is an important exam that determines my career in Turkey, I will take the exam on June 8th and I don't have much time, I have cut a lot of time, but this is temporary and I will come back and complete the exercises to 20, I just wanted to mention the reason why the process has slowed down.

**Comment by ErikSchierboom** [comment]
Sure. Good luck!

**Comment by GroophyLifefor** [comment]
It's been 20 exercises, what should we do now?

**Comment by ErikSchierboom** [comment]
Basically just to follow the steps listed above. So next up would be to setup continuous integration.

**Comment by GroophyLifefor** [comment]
> Basically just to follow the steps listed above. So next up would be to setup continuous integration.

I had a little familiarity with docker, I could basically do something with it, -although not very detailed-. but I'm really completely stuck on the test.yaml file. i couldn't even test it on my local, i got an error when i tried docker-compose. i'm not clear on how to install wine with yaml, how to bind to unix* and run test cases.

**Comment by ErikSchierboom** [comment]
You can't test github actions locally, which is admittedly annoying. For CI, we can do two things:
1. Use a Windows test runner and run the scripts
2. Use a Linux test runner and use the test runner Docker image I'll have a think

**Comment by GroophyLifefor** [comment]
just to be sure, if I write a terminal code that will test all the exercises in the terminal in windows operating system and this terminal's native language is batch language, can we run it as a test-runner? but as I said, batch language natively supports only windows.

**Comment by ErikSchierboom** [comment]
> if I write a terminal code that will test all the exercises in the terminal in windows operating system and this terminal's native language is batch language, can we run it as a test-runner

No, because we can't run Windows docker images in our production environment. But such a script _could_ run in CI, so yes, that would be really helpful.

**Comment by GroophyLifefor** [comment]
Hi, I made an test-runner experiment and It looks good for now, but the batch language is native to the windows operating system, so it works with the efficiency of an emulator, which means that unfortunately some exercises did not pass the test-runner.

you can see the experimental branch: https://github.com/exercism/batch/tree/test-runner
shell script(Unix* shell script): https://github.com/exercism/batch/blob/test-runner/bin/test-runner.sh
linked called test-runner(batchfile and works on wine): https://github.com/exercism/batch/blob/test-runner/bin/test-runner.bat

---

here one image which works well:

![image](https://github.com/user-attachments/assets/001d7fc1-6db2-4a78-ba2b-6dd4440c0ca5)

---

here one which different to windows: (should be all passed)

![image](https://github.com/user-attachments/assets/56c54d6f-0741-4cb4-9555-939ae8255bd1)

---

here one which got crashed:

![image](https://github.com/user-attachments/assets/1d987aac-5010-479a-8629-6e01de1d9999)
![image](https://github.com/user-attachments/assets/2aa8b639-3b05-4072-892b-7ae4e7cf2b8e)

**Comment by ErikSchierboom** [comment]
I assume that the failing solutions don't do anything "weird"?

p.s.

> I made an test-runner experiment
The test runner name is something we use for, well, test runners, like https://github.com/exercism/batch-test-runner You might want to call this a CI script of test verification script or something to reduce confusion.

**Comment by GroophyLifefor** [comment]
I guess I don't understand what you mean, batch is a very complex language (as interpreter) and even an advanced tool like wine can't emulate it as well as windows. Every language works best in its natural environment.

**Comment by ErikSchierboom** [comment]
Okay, clear.

@iHiD It sounds like the Batch track might not work well on Linux, which is sort of to be expected. Do we still want a test runner, even if that fails for perfectly valid solutions? I also assume that most people doing the Batch track will work on Windows. Do we maybe want to disable the test runner for this track?

**Comment by GroophyLifefor** [comment]
Hi @ErikSchierboom , Is there any news to move? @iHiD might not have seen your comment.

**Comment by ErikSchierboom** [comment]
I'll notify him

**Comment by ErikSchierboom** [comment]
We've discussed this and we think it's better to just disable the test runner and focus solely on Windows. Can you fix CI to work on Windows and then use your script to verify the exercises?

**Comment by GroophyLifefor** [comment]
Well, I'll do as soon as.

**Comment by GroophyLifefor** [comment]
Here new version: https://github.com/exercism/batch/blob/test-runner/bin/test-runner.bat

**Comment by ErikSchierboom** [comment]
I have pushed some changes to your branch to setup CI: https://github.com/exercism/batch/pull/41
Whilst CI appears to be succeeding, I don't think that is actually the case.
I see this in the log:

```
Run bin/verify-exercises.bat
  bin/verify-exercises.bat
  shell: C:\Windows\system3[2](https://github.com/exercism/batch/actions/runs/10281842917/job/28452234171?pr=41#step:3:2)\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
The system cannot find the file config.json.
```

Could you look at that?

**Comment by GroophyLifefor** [comment]
@ErikSchierboom Sorry for much push but CI got fixed :)

![image](https://github.com/user-attachments/assets/78bdf980-e5b3-4c47-855c-0117b7150ee2)

**Comment by ErikSchierboom** [comment]
@GroophyLifefor Great. Could you purposefully have one example implementation fail one or more tests to see if CI then fails?

**Comment by GroophyLifefor** [comment]
@ErikSchierboom it was great, even if the exercise is faulty it continues but since it was in the last exercise the test is completely finished, no problem 

![image](https://github.com/user-attachments/assets/b2cdef33-a914-4ca8-a90c-50ed67bbc958)

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by GroophyLifefor** [comment]
@ErikSchierboom so, is "Setup Continuous Integration" part done? What is the next step?

**Comment by ErikSchierboom** [comment]
@GroophyLifefor check the steps at https://exercism.org/docs/building/tracks/new to see what needs to be done next

**Comment by GroophyLifefor** [comment]
Reference to a pr that about this issue: https://github.com/exercism/cli/pull/1157

**Comment by GroophyLifefor** [comment]
@ErikSchierboom Can I start maintaining alone? I think over time people will come, it's hard to find someone at this stage (not launched).

**Comment by ErikSchierboom** [comment]
Yes that is fine

**Comment by GroophyLifefor** [comment]
@ErikSchierboom when https://exercism.org/tracks/batch will be activated?

**Comment by ErikSchierboom** [comment]
@GroophyLifefor It'll be up in about 10 minutes or so!

**Comment by BNAndras** [comment]
https://exercism.org/tracks/batch is missing a track icon. Was it supposed to go live already?

**Comment by GroophyLifefor** [comment]
> https://exercism.org/tracks/batch is missing a track icon. Was it supposed to go live already?

I submitted in https://github.com/exercism/website-icons/issues/179 two weeks ago, It's now fixed, we apologize for the inconvenience

**Comment by BNAndras** [comment]
Track is launched so we can close this issue.
